name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install babel-eslint eslint-plugin-import eslint-config-airbnb-base eslint-plugin-babel
          make lint
