name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install jest babel-jest @babel/core @babel/preset-env @babel/plugin-proposal-pipeline-operator
          make test
